services:

  # SQL Database
  postgres:
    image: docker.io/postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: epoch_pg 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    ports:
      - 5432:5432

