//! Saga definition

use crate::event::{EnumConversionError, Event, EventData};
use crate::prelude::{EventObserver, StateStoreBackend};
use async_trait::async_trait;
use std::marker::PhantomData;
use std::sync::Arc;
use uuid::Uuid;

/// Defines the errors that can happen when handling an event in a saga.
///
/// Note: Conversion failures (when converting from a superset event to the saga's
/// subset event type) are intentionally ignored in `process_event()`. This is expected
/// behavior since sagas only handle events from their subset.
#[derive(Debug, thiserror::Error)]
pub enum HandleEventError<S, E> {
    /// An error raised while handling the event
    #[error("Error while handling event: {0}")]
    Saga(S),
    /// An error raised by the state store
    #[error("Error while storing state: {0}")]
    State(E),
}

/// `Saga` is a trait that defines the interface for a saga in an event-sourced system.
/// A saga is a long-running business process that is coordinated by a series of local transactions.
///
/// # Subscriber ID
///
/// Implementors must also implement [`SubscriberId`](crate::SubscriberId) to provide
/// a unique identifier for checkpoint tracking, multi-instance coordination, and
/// dead letter queue association. Use the `#[derive(SubscriberId)]` macro from
/// `epoch_derive` for automatic implementation:
///
/// ```ignore
/// use epoch_derive::SubscriberId;
///
/// #[derive(SubscriberId)]
/// #[subscriber_id(prefix = "saga")]
/// struct OrderFulfillmentSaga { /* ... */ }
/// // Automatically implements SubscriberId with subscriber_id() -> "saga:order-fulfillment"
/// ```
///
/// # Event Observer Integration
///
/// To subscribe a saga to an event bus, wrap it in [`SagaHandler`] which provides the
/// [`EventObserver`] implementation. This is necessary because [`Projection`](crate::projection::Projection)
/// already has a blanket `EventObserver` impl, and Rust doesn't allow multiple blanket impls.
///
/// # Example
///
/// ```ignore
/// use epoch_core::saga::SagaHandler;
/// use epoch_derive::SubscriberId;
///
/// #[derive(SubscriberId)]
/// #[subscriber_id(prefix = "saga")]
/// struct MySaga { /* ... */ }
///
/// #[async_trait]
/// impl Saga<ApplicationEvent> for MySaga {
///     type State = MySagaState;
///     type StateStore = MyStateStore;
///     type SagaError = MySagaError;
///     type EventType = MySagaEvent;
///
///     fn get_state_store(&self) -> Self::StateStore { /* ... */ }
///
///     async fn handle_event(
///         &self,
///         state: Self::State,
///         event: &Event<Self::EventType>,  // Note: takes reference
///     ) -> Result<Option<Self::State>, Self::SagaError> {
///         match &event.data {
///             MySagaEvent::SomethingHappened { .. } => { /* ... */ }
///         }
///     }
/// }
///
/// // Wrap in SagaHandler to subscribe to the event bus
/// let saga = MySaga::new();
/// event_bus.subscribe(SagaHandler::new(saga)).await?;
/// ```
#[async_trait]
pub trait Saga<ED>: crate::SubscriberId
where
    ED: EventData + Send + Sync + 'static,
{
    /// The type of the state of the saga. This acts as a state machine. It should be defined as an
    /// enum
    type State: Send + Sync + Default;
    /// The type of `StateStorage` used by this `Saga`.
    type StateStore: StateStoreBackend<Self::State> + Send + Sync;
    /// The type of errors that may occur when handling events in this `Saga`.
    type SagaError: std::error::Error + Send + Sync + 'static;
    /// The type of event used by this saga.
    ///
    /// Must implement `TryFrom<&ED, Error = EnumConversionError>` for efficient
    /// reference-based conversion. This is automatically generated by the `#[subset_enum]` macro.
    type EventType: EventData + for<'a> TryFrom<&'a ED, Error = EnumConversionError>;

    /// Returns the `StateStorage` implementation for this `Saga`.
    fn get_state_store(&self) -> Self::StateStore;

    /// Handles an incoming event, potentially producing and dispatching commands.
    ///
    /// The event is passed by reference to avoid unnecessary cloning. If you need to
    /// retain the event data, you can clone the specific fields you need.
    async fn handle_event(
        &self,
        state: Self::State,
        event: &Event<Self::EventType>,
    ) -> Result<Option<Self::State>, Self::SagaError>;

    /// Returns the ID of the saga from the given event.
    fn get_id_from_event(&self, event: &Event<Self::EventType>) -> Uuid {
        event.stream_id
    }

    /// Processing priority for event bus ordering.
    ///
    /// Lower values are processed first. Convention:
    /// - `0`: Projections (via `ProjectionHandler`)
    /// - `50`: Complex projections using the `Saga` trait
    /// - `100`: Sagas (default)
    fn priority(&self) -> u8 {
        100
    }

    /// Processes an incoming event, applies it to the saga, and persists the resulting state.
    ///
    /// This method is called by the blanket [`EventObserver`] implementation. It handles:
    /// 1. Converting the event to the saga's event type via [`Event::to_subset_event`]
    /// 2. Loading the current saga state from the state store
    /// 3. Calling [`Saga::handle_event`] with the state and event
    /// 4. Persisting or deleting the resulting state
    ///
    /// The event is passed by reference to avoid unnecessary cloning.
    async fn process_event(
        &self,
        event: &Event<ED>,
    ) -> Result<
        (),
        HandleEventError<
            Self::SagaError,
            <Self::StateStore as StateStoreBackend<Self::State>>::Error,
        >,
    > {
        if let Ok(event) = event.to_subset_event_ref::<Self::EventType>() {
            let id = self.get_id_from_event(&event);
            let mut storage = self.get_state_store();
            let state = storage
                .get_state(id)
                .await
                .map_err(HandleEventError::State)?
                .unwrap_or_default();

            let state = self
                .handle_event(state, &event)
                .await
                .map_err(HandleEventError::Saga)?;

            if let Some(state) = state {
                storage
                    .persist_state(id, state)
                    .await
                    .map_err(HandleEventError::State)?;
            } else {
                storage
                    .delete_state(id)
                    .await
                    .map_err(HandleEventError::State)?;
            }
        }
        Ok(())
    }
}

/// Blanket [`Saga`] implementation for `Arc<S>` where `S: Saga<ED>`.
///
/// This allows an `Arc`-wrapped saga to be used directly with [`SagaHandler`] and
/// [`SagaAdapter`], enabling shared ownership across multiple bus subscriptions:
///
/// ```ignore
/// let saga = Arc::new(MySaga::new(...));
/// native_bus.subscribe(SagaHandler::new(saga.clone())).await?;
/// foreign_bus.subscribe(SagaAdapter::new(saga.clone(), "saga:my:foreign", |e| ...)).await?;
/// ```
#[async_trait]
impl<ED, S> Saga<ED> for Arc<S>
where
    ED: EventData + Send + Sync + 'static,
    S: Saga<ED> + Send + Sync,
    S::EventType: Sync,
{
    type State = S::State;
    type StateStore = S::StateStore;
    type SagaError = S::SagaError;
    type EventType = S::EventType;

    fn get_state_store(&self) -> Self::StateStore {
        (**self).get_state_store()
    }

    async fn handle_event(
        &self,
        state: Self::State,
        event: &Event<Self::EventType>,
    ) -> Result<Option<Self::State>, Self::SagaError> {
        (**self).handle_event(state, event).await
    }

    fn get_id_from_event(&self, event: &Event<Self::EventType>) -> Uuid {
        (**self).get_id_from_event(event)
    }

    fn priority(&self) -> u8 {
        (**self).priority()
    }
}

/// A wrapper type that provides an [`EventObserver`] implementation for [`Saga`] types.
///
/// Since Rust doesn't allow multiple blanket implementations of the same trait, and
/// [`Projection`](crate::projection::Projection) already has a blanket `EventObserver` impl,
/// sagas must be wrapped in `SagaHandler` to be subscribed to an event bus.
///
/// # Example
///
/// ```ignore
/// use epoch_core::saga::SagaHandler;
///
/// let saga = MySaga::new();
/// let handler = SagaHandler::new(saga);
/// event_bus.subscribe(handler).await?;
/// ```
pub struct SagaHandler<S>(pub S);

impl<S> SagaHandler<S> {
    /// Creates a new `SagaHandler` wrapping the given saga.
    pub fn new(saga: S) -> Self {
        Self(saga)
    }

    /// Returns a reference to the inner saga.
    pub fn inner(&self) -> &S {
        &self.0
    }

    /// Consumes the handler and returns the inner saga.
    pub fn into_inner(self) -> S {
        self.0
    }
}

impl<S> crate::SubscriberId for SagaHandler<S>
where
    S: crate::SubscriberId,
{
    fn subscriber_id(&self) -> &str {
        self.0.subscriber_id()
    }
}

#[async_trait]
impl<ED, S> EventObserver<ED> for SagaHandler<S>
where
    ED: EventData + Send + Sync + 'static,
    S: Saga<ED> + Send + Sync,
{
    async fn on_event(
        &self,
        event: Arc<Event<ED>>,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        self.0.process_event(&event).await?;
        Ok(())
    }

    /// Delegates to the inner saga's [`Saga::priority`] method.
    fn priority(&self) -> u8 {
        self.0.priority()
    }
}

/// Adapter that lets a [`Saga`] subscribe to a *foreign* event bus carrying a
/// different parent event enum.
///
/// A saga is parameterized over a single parent event type (its "native" bus).
/// When the saga also needs to react to events from a second bus whose parent
/// enum is unrelated, wrap the saga in a `SagaAdapter` and register the
/// adapter on the foreign bus. The adapter:
///
/// 1. Receives `Event<SourceEvent>` from the foreign bus.
/// 2. Calls the user-supplied converter `Fn(&SourceEvent) -> Option<TargetEvent>`
///    to produce data in the saga's native parent type. Returning `None`
///    silently skips the event (the foreign bus's checkpoint still advances).
/// 3. Rebuilds an `Event<TargetEvent>` preserving all metadata fields
///    (`id`, `stream_id`, `stream_version`, `event_type`, `actor_id`,
///    `purger_id`, `created_at`, `purged_at`, `global_sequence`,
///    `causation_id`, `correlation_id`).
/// 4. Delegates to [`Saga::process_event`] on the wrapped saga, which projects
///    to the saga's `EventType` subset and runs `handle_event` as usual.
///
/// # Checkpointing
///
/// Each `SagaAdapter` instance carries its own `subscriber_id`, which the
/// event bus uses to key its checkpoint row. The same saga can be subscribed
/// to N buses by constructing N adapters with N distinct subscriber IDs;
/// each subscription advances independently.
///
/// The wrapped saga's own `subscriber_id()` (used as the state-store key in
/// the default `Saga::process_event` flow) is left untouched, so saga
/// instances share state across all bus subscriptions.
///
/// # Example
///
/// ```ignore
/// // BillingSaga is native to BillingEvent but also needs ComputeEvent
/// // signals (e.g. MachineProvisioned).
/// let saga = Arc::new(BillingSaga::new(/* ... */));
///
/// // Native bus: standard SagaHandler.
/// billing_bus.subscribe(SagaHandler::new(saga.clone())).await?;
///
/// // Foreign bus: SagaAdapter with explicit subscriber id + converter.
/// compute_bus
///     .subscribe(SagaAdapter::new(
///         saga.clone(),
///         "saga:billing:compute-bus",
///         |e: &ComputeEvent| match e {
///             ComputeEvent::MachineProvisioned { pool_id, .. } => {
///                 Some(BillingEvent::CapacityIncreased { pool_id: *pool_id })
///             }
///             _ => None,
///         },
///     ))
///     .await?;
/// ```
pub struct SagaAdapter<S, SourceEvent, TargetEvent, F>
where
    S: Saga<TargetEvent>,
    SourceEvent: EventData + Send + Sync + 'static,
    TargetEvent: EventData + Send + Sync + 'static,
    F: Fn(&SourceEvent) -> Option<TargetEvent> + Send + Sync,
{
    saga: Arc<S>,
    subscriber_id: String,
    converter: F,
    _marker: PhantomData<fn(SourceEvent) -> TargetEvent>,
}

impl<S, SourceEvent, TargetEvent, F> SagaAdapter<S, SourceEvent, TargetEvent, F>
where
    S: Saga<TargetEvent>,
    SourceEvent: EventData + Send + Sync + 'static,
    TargetEvent: EventData + Send + Sync + 'static,
    F: Fn(&SourceEvent) -> Option<TargetEvent> + Send + Sync,
{
    /// Creates a new `SagaAdapter`.
    ///
    /// * `saga` - `Arc`-wrapped saga shared across bus subscriptions. Both
    ///   [`SagaHandler`] and `SagaAdapter` accept `Arc<S>` (via the blanket
    ///   `Saga` impl for `Arc<S>`), so a single `Arc::new(saga)` can back
    ///   any number of adapters without cloning internal state.
    /// * `subscriber_id` - Unique identifier for *this specific subscription*.
    ///   Used by the event bus to track an independent checkpoint per bus.
    ///   Convention: `"saga:<saga-name>:<source-bus-name>"`.
    /// * `converter` - Closure mapping the foreign bus's event variants into
    ///   the saga's native parent event type. Return `None` to skip events
    ///   the saga does not care about.
    pub fn new(saga: Arc<S>, subscriber_id: impl Into<String>, converter: F) -> Self {
        Self {
            saga,
            subscriber_id: subscriber_id.into(),
            converter,
            _marker: PhantomData,
        }
    }

    /// Returns a reference to the inner saga.
    pub fn inner(&self) -> &S {
        &self.saga
    }
}

impl<S, SourceEvent, TargetEvent, F> crate::SubscriberId
    for SagaAdapter<S, SourceEvent, TargetEvent, F>
where
    S: Saga<TargetEvent> + Send + Sync,
    SourceEvent: EventData + Send + Sync + 'static,
    TargetEvent: EventData + Send + Sync + 'static,
    F: Fn(&SourceEvent) -> Option<TargetEvent> + Send + Sync,
{
    fn subscriber_id(&self) -> &str {
        &self.subscriber_id
    }
}

#[async_trait]
impl<S, SourceEvent, TargetEvent, F> EventObserver<SourceEvent>
    for SagaAdapter<S, SourceEvent, TargetEvent, F>
where
    S: Saga<TargetEvent> + Send + Sync,
    SourceEvent: EventData + Send + Sync + 'static,
    TargetEvent: EventData + Send + Sync + 'static,
    F: Fn(&SourceEvent) -> Option<TargetEvent> + Send + Sync + 'static,
{
    async fn on_event(
        &self,
        event: Arc<Event<SourceEvent>>,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let Some(source_data) = event.data.as_ref() else {
            return Ok(());
        };
        let Some(target_data) = (self.converter)(source_data) else {
            return Ok(());
        };
        let target_event = Event {
            id: event.id,
            stream_id: event.stream_id,
            stream_version: event.stream_version,
            event_type: event.event_type.clone(),
            actor_id: event.actor_id,
            purger_id: event.purger_id,
            data: Some(target_data),
            created_at: event.created_at,
            purged_at: event.purged_at,
            global_sequence: event.global_sequence,
            causation_id: event.causation_id,
            correlation_id: event.correlation_id,
            schema_version: event.schema_version,
        };
        self.saga.as_ref().process_event(&target_event).await?;
        Ok(())
    }

    fn priority(&self) -> u8 {
        self.saga.priority()
    }
}
